import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContentWrapper from "@/_components/ContentWrapper";

export const metadata = {
  title: "MeraDhan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
